version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release
  - Debug

install:
    - git submodule update --init --recursive

before_build:
    - cmake -DBUILD_DOC=OFF -DBUILD_DEMO=OFF -BUILD_BENCH=OFF -BUILD_TEST=ON -G "Visual Studio 15 2017 Win64" .
    - cd $(APPVEYOR_BUILD_FOLDER)
    - dir
build:
  project: $(APPVEYOR_BUILD_FOLDER)/unit-test.sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%/CONFIGURATION%/Test/unit-test.exe'